"""
installers/common/env_writer.py — Safe Environment File Writer
Synthos · shared installer helper

Writes .env files with these guarantees:
  - Existing files are NEVER silently overwritten
  - A timestamped backup is created before any write
  - Writes are atomic (temp file → rename)
  - File permissions are set to 600 after write
  - No secret values are logged at any level

Rules enforced:
  - If the target path exists → backup first, then write
  - If write fails → backup is preserved, original is untouched
  - chmod 600 always applied after successful write
"""

import logging
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

log = logging.getLogger("installer.env_writer")


def _backup_existing(env_path: Path) -> Optional[Path]:
    """
    Copy existing env file to a timestamped backup.
    Returns the backup path, or None if no existing file.
    """
    if not env_path.exists():
        return None
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    backup_path = env_path.with_name(f".env.backup_{ts}")
    shutil.copy2(env_path, backup_path)
    os.chmod(backup_path, 0o600)
    log.info("Existing .env backed up to %s", backup_path.name)
    return backup_path


def write_env(env_path: Path, content: str) -> Path:
    """
    Write env content to env_path atomically.

    - If file exists: backs up first, then writes
    - Uses temp file + rename for atomicity
    - Sets chmod 600 on result
    - Returns final path

    Raises:
        OSError: if write or rename fails (backup preserved if applicable)
    """
    # Ensure parent directory exists
    env_path.parent.mkdir(parents=True, exist_ok=True)

    # Backup existing file
    backup = _backup_existing(env_path)

    tmp_path = env_path.with_name(".env.tmp")
    try:
        tmp_path.write_text(content, encoding="utf-8")
        tmp_path.replace(env_path)
        os.chmod(env_path, 0o600)
        log.info("Wrote %s (%d bytes, chmod 600)", env_path, env_path.stat().st_size)
    except OSError as exc:
        log.error("Failed to write env file: %s", exc)
        # Clean up temp if it exists
        if tmp_path.exists():
            tmp_path.unlink(missing_ok=True)
        raise

    return env_path


def build_retail_env(config: dict, generated_secret_key: str) -> str:
    """
    Build the .env file content for a retail node.
    All values come from config dict (collected by wizard).
    PORTAL_SECRET_KEY is generated externally and passed in.
    ENCRYPTION_KEY is generated fresh here if not already in config (repair mode
    preserves the existing key via the _env_to_wizard map in install_retail.py).
    Returns the full file content as a string.
    """
    from cryptography.fernet import Fernet
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # Preserve existing key on repair; generate fresh on first install
    encryption_key = config.get('encryption_key') or Fernet.generate_key().decode()

    lines = [
        f"# Synthos Retail Node — Environment Configuration",
        f"# Generated by install_retail.py on {now}",
        f"# DO NOT SHARE — contains private credentials",
        f"# chmod 600 enforced by installer",
        f"",
        f"# ── ENCRYPTION ────────────────────────────────────────────────",
        f"# Generated once at install. Never regenerate — doing so destroys all",
        f"# encrypted customer data (emails, passwords, Alpaca credentials).",
        f"ENCRYPTION_KEY={encryption_key}",
        f"",
        f"# ── SYSTEM IDENTITY ───────────────────────────────────────────",
        f"PI_ID={config.get('pi_id', 'synthos-pi-1')}",
        f"PI_LABEL={config.get('pi_label', '')}",
        f"PI_EMAIL={config.get('pi_email', '')}",
        f"",
        f"# ── ADMIN ACCOUNT ─────────────────────────────────────────────",
        f"# Portal admin credentials — set during install.",
        f"ADMIN_NAME={config.get('admin_name', '')}",
        f"ADMIN_EMAIL={config.get('admin_email', '')}",
        f"ADMIN_PASSWORD={config.get('admin_password', '')}",
        f"",
        f"# ── OWNER CUSTOMER ACCOUNT ────────────────────────────────────",
        f"# Mirrors admin credentials — single-operator setup.",
        f"OWNER_NAME={config.get('admin_name', '')}",
        f"OWNER_EMAIL={config.get('admin_email', '')}",
        f"OWNER_PASSWORD={config.get('admin_password', '')}",
        f"# 'standard' or 'early_adopter' — controls which pricing experience you see.",
        f"OWNER_PRICING_TIER=standard",
        f"# Populated automatically on first portal startup — do not edit manually.",
        f"OWNER_CUSTOMER_ID=",
        f"",
        f"# ── TRADING SETTINGS ──────────────────────────────────────────",
        f"STARTING_CAPITAL={config.get('starting_capital', '1000')}",
        f"OPERATING_MODE={config.get('operating_mode', 'MANAGED')}",
        f"AUTONOMOUS_UNLOCK_KEY=",
        f"TRADING_MODE=PAPER",
        f"CLOSE_SESSION_MODE=conservative",
        f"MAX_POSITION_PCT=0.10",
        f"MAX_SECTOR_PCT=25",
        f"",
        f"# ── PORTAL ────────────────────────────────────────────────────",
        f"PORTAL_PORT={config.get('portal_port', '5001')}",
        f"PORTAL_PASSWORD={config.get('portal_password', '')}",
        f"PORTAL_SECRET_KEY={generated_secret_key}",
        f"# Set to your Cloudflare tunnel URL once active.",
        f"PORTAL_BASE_URL=",
        f"SUPPORT_EMAIL=synthos.signal@gmail.com",
        f"",
        f"# ── API KEYS — restore from backup ────────────────────────────",
        f"# These are intentionally blank after a fresh install.",
        f"# Restore your backup archive to populate them, or enter manually.",
        f"ANTHROPIC_API_KEY=",
        f"ALPACA_API_KEY=",
        f"ALPACA_SECRET_KEY=",
        f"ALPACA_BASE_URL=https://paper-api.alpaca.markets",
        f"LICENSE_KEY=",
        f"",
        f"# ── NETWORK NODES ────────────────────────────────────────────",
        f"# Monitor node: pi2w_monitor_node (Raspberry Pi Zero 2W, LAN-only)",
        f"# DHCP-assigned IP — update to static IP when ethernet switch is installed.",
        f"# MONITOR_TOKEN must exactly match SECRET_TOKEN on pi2w_monitor_node .env",
        f"# See MEMORY.md — Future Planning Notes for IP finalization checklist.",
        f"MONITOR_URL=http://192.168.203.10:5000",
        f"MONITOR_TOKEN=synthos-default-token",
        f"# Company node: pi4b — forwards alerts and event queue",
        f"# Update IP alongside MONITOR_URL when ethernet switch is installed.",
        f"COMPANY_URL=http://192.168.206.172:5010",
        f"",
        f"# ── ALERTS — restore from backup ──────────────────────────────",
        f"RESEND_API_KEY=",
        f"ALERT_FROM=",
        f"USER_EMAIL=",
        f"GMAIL_USER=",
        f"GMAIL_APP_PASSWORD=",
        f"ALERT_PHONE=",
        f"CARRIER_GATEWAY=tmomail.net",
        f"",
        f"# ── OPTIONAL ──────────────────────────────────────────────────",
        f"GITHUB_TOKEN=",
        f"# ── SCOOP VOLUME CONTROLS ─────────────────────────────────────",
        f"# Master dispatch switch. Set to true when ready to send email alerts.",
        f"SCOOP_ENABLED=false",
        f"# 0=critical only  1=+high  2=+medium  3=all",
        f"SCOOP_MIN_PRIORITY=0",
        f"# ── STRONGBOX ─────────────────────────────────────────────────",
        f"STRONGBOX_STALE_HOURS=48",
        f"PI_EVENTS_RETAIN_DAYS=30",
        f"",
    ]
    return "\n".join(lines)


def build_monitor_env(config: dict) -> str:
    """
    Build the .env file content for a Monitor Node (any Pi).
    Used by synthos_monitor.py (Flask, port 5000).
    Returns the full file content as a string.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        f"# Synthos Monitor Node — Environment Configuration",
        f"# Generated by install_monitor.py on {now}",
        f"# DO NOT SHARE — contains authentication token",
        f"# chmod 600 enforced by installer",
        f"",
        f"# ── NODE IDENTITY ─────────────────────────────────────────────",
        f"# Shared with all retail Pis as MONITOR_TOKEN.",
        f"SECRET_TOKEN={config.get('secret_token', '')}",
        f"PORT={config.get('port', '5000')}",
        f"",
        f"# ── ALERT WINDOW ──────────────────────────────────────────────",
        f"# Hours during which silence alerts are sent (Eastern).",
        f"ALERT_START_HOUR={config.get('alert_start_hour', '8')}",
        f"ALERT_END_HOUR={config.get('alert_end_hour', '20')}",
        f"",
        f"# ── OPS CONTACT ───────────────────────────────────────────────",
        f"# Where silence alerts are sent.",
        f"ALERT_TO={config.get('alert_to', '')}",
        f"# The verified sender address in your Resend account.",
        f"ALERT_FROM={config.get('alert_from', '')}",
        f"",
        f"# ── RESEND — add after install ────────────────────────────────",
        f"# Intentionally blank after fresh install.",
        f"# Add your Resend API key here to activate silence email alerts.",
        f"RESEND_API_KEY=",
        f"",
        f"# ── COMPANY PI INTEGRATION ────────────────────────────────────",
        f"# Optional. If set, monitor forwards events to the Company Pi.",
        f"COMPANY_URL={config.get('company_url', '')}",
        f"",
    ]
    return "\n".join(lines)


def build_company_env(config: dict) -> str:
    """
    Build the .env file content for a Company Node (Pi 4B).
    Used by company_server.py (Flask, port 5010) and scoop.py (queue drain daemon).
    Returns the full file content as a string.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        f"# Synthos Company Node — Environment Configuration",
        f"# Generated by install_company.py on {now}",
        f"# DO NOT SHARE — contains company secrets",
        f"# chmod 600 enforced by installer",
        f"",
        f"# ── NODE IDENTITY ─────────────────────────────────────────────",
        f"COMPANY_MODE=true",
        f"SECRET_TOKEN={config.get('secret_token', '')}",
        f"PORT={config.get('port', '5010')}",
        f"",
        f"# ── DATABASE ──────────────────────────────────────────────────",
        f"COMPANY_DB_PATH={config.get('company_db_path', '')}",
        f"",
        f"# ── OPS CONTACT ───────────────────────────────────────────────",
        f"# Where operational alerts are routed once keys are restored.",
        f"OPS_EMAIL={config.get('ops_email', '')}",
        f"OPERATOR_EMAIL={config.get('ops_email', '')}",
        f"",
        f"# ── RESEND — restore from backup ──────────────────────────────",
        f"# Intentionally blank after fresh install. Restore from backup.",
        f"RESEND_API_KEY=",
        f"ALERT_FROM=",
        f"ALERT_TO=",
        f"",
        f"# ── SCOOP SETTINGS ────────────────────────────────────────────",
        f"# Master dispatch switch. Set to true when ready to receive email alerts.",
        f"SCOOP_ENABLED={config.get('scoop_enabled', 'false')}",
        f"# Minimum priority to dispatch: 0=critical only  1=+high  2=+medium  3=all",
        f"SCOOP_MIN_PRIORITY={config.get('scoop_min_priority', '0')}",
        f"SCOOP_POLL_S={config.get('scoop_poll_s', '5')}",
        f"SCOOP_MAX_ATTEMPTS={config.get('scoop_max_attempts', '3')}",
        f"SCOOP_RETRY_DELAY_S={config.get('scoop_retry_delay_s', '60')}",
        f"SCOOP_DRY_RUN={config.get('scoop_dry_run', 'false')}",
        f"",
        f"# ── STRONGBOX SETTINGS ────────────────────────────────────────",
        f"# Hours before a missing backup triggers a CRITICAL alert (default 48).",
        f"STRONGBOX_STALE_HOURS={config.get('strongbox_stale_hours', '48')}",
        f"# Days of pi_events heartbeat history to keep in company.db (default 30).",
        f"PI_EVENTS_RETAIN_DAYS={config.get('pi_events_retain_days', '30')}",
        f"",
        f"# ── SENTINEL DISPLAY ──────────────────────────────────────────",
        f"# Set to 'true' if a display was detected during installation.",
        f"# SENTINEL_HOME points to the Sentinel display project root.",
        f"DISPLAY_DETECTED={config.get('display_detected', 'false')}",
        f"SENTINEL_HOME={config.get('sentinel_home', '/home/pi/sentinel')}",
        f"SENTINEL_STATE=/tmp/sentinel_state.json",
        f"DISPLAY_DROP_DIR={config.get('display_drop_dir', '')}",
        f"",
        f"# ── GITHUB PROJECT STATUS ─────────────────────────────────────",
        f"# Personal access token (read:contents scope only).",
        f"# Used by /project-status to pull project_status.json from GitHub.",
        f"# Leave blank to fall back to local data/project_status.json.",
        f"GITHUB_TOKEN=",
        f"GITHUB_REPO_OWNER={config.get('github_owner', 'personalprometheus-blip')}",
        f"GITHUB_STATUS_REPO={config.get('github_status_repo', 'synthos-company')}",
        f"GITHUB_STATUS_PATH={config.get('github_status_path', 'data/project_status.json')}",
        f"# Cache TTL in seconds (default 300 = 5 minutes).",
        f"PROJECT_STATUS_TTL={config.get('project_status_ttl', '300')}",
        f"",
    ]
    return "\n".join(lines)
