"""
installers/common/env_writer.py — Safe Environment File Writer
Synthos · shared installer helper

Writes .env files with these guarantees:
  - Existing files are NEVER silently overwritten
  - A timestamped backup is created before any write
  - Writes are atomic (temp file → rename)
  - File permissions are set to 600 after write
  - No secret values are logged at any level

Rules enforced:
  - If the target path exists → backup first, then write
  - If write fails → backup is preserved, original is untouched
  - chmod 600 always applied after successful write
"""

import logging
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

log = logging.getLogger("installer.env_writer")


def _backup_existing(env_path: Path) -> Optional[Path]:
    """
    Copy existing env file to a timestamped backup.
    Returns the backup path, or None if no existing file.
    """
    if not env_path.exists():
        return None
    ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    backup_path = env_path.with_name(f".env.backup_{ts}")
    shutil.copy2(env_path, backup_path)
    os.chmod(backup_path, 0o600)
    log.info("Existing .env backed up to %s", backup_path.name)
    return backup_path


def write_env(env_path: Path, content: str) -> Path:
    """
    Write env content to env_path atomically.

    - If file exists: backs up first, then writes
    - Uses temp file + rename for atomicity
    - Sets chmod 600 on result
    - Returns final path

    Raises:
        OSError: if write or rename fails (backup preserved if applicable)
    """
    # Ensure parent directory exists
    env_path.parent.mkdir(parents=True, exist_ok=True)

    # Backup existing file
    backup = _backup_existing(env_path)

    tmp_path = env_path.with_name(".env.tmp")
    try:
        tmp_path.write_text(content, encoding="utf-8")
        tmp_path.replace(env_path)
        os.chmod(env_path, 0o600)
        log.info("Wrote %s (%d bytes, chmod 600)", env_path, env_path.stat().st_size)
    except OSError as exc:
        log.error("Failed to write env file: %s", exc)
        # Clean up temp if it exists
        if tmp_path.exists():
            tmp_path.unlink(missing_ok=True)
        raise

    return env_path


def build_retail_env(config: dict, generated_secret_key: str) -> str:
    """
    Build the .env file content for a retail node.
    All values come from config dict (collected by wizard).
    PORTAL_SECRET_KEY is generated externally and passed in.
    Returns the full file content as a string.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        f"# Synthos Retail Node — Environment Configuration",
        f"# Generated by install_retail.py on {now}",
        f"# DO NOT SHARE — contains private API keys",
        f"# chmod 600 enforced by installer",
        f"",
        f"# ── CORE API KEYS ─────────────────────────────────────────────",
        f"ANTHROPIC_API_KEY={config.get('anthropic_key', '')}",
        f"ALPACA_API_KEY={config.get('alpaca_key', '')}",
        f"ALPACA_SECRET_KEY={config.get('alpaca_secret', '')}",
        f"ALPACA_BASE_URL={config.get('alpaca_base_url', 'https://paper-api.alpaca.markets')}",
        f"TRADING_MODE={config.get('trading_mode', 'PAPER')}",
        f"",
        f"# ── OPERATING MODE ────────────────────────────────────────────",
        f"OPERATING_MODE={config.get('operating_mode', 'SUPERVISED')}",
        f"AUTONOMOUS_UNLOCK_KEY={config.get('autonomous_unlock_key', '')}",
        f"",
        f"# ── LICENSE ───────────────────────────────────────────────────",
        f"LICENSE_KEY={config.get('license_key', '')}",
        f"",
        f"# ── SYSTEM IDENTITY ───────────────────────────────────────────",
        f"PI_ID={config.get('pi_id', 'synthos-pi-1')}",
        f"PI_LABEL={config.get('pi_label', '')}",
        f"PI_EMAIL={config.get('pi_email', '')}",
        f"OWNER_NAME={config.get('owner_name', '')}",
        f"OWNER_EMAIL={config.get('owner_email', '')}",
        f"OWNER_PASSWORD={config.get('owner_password', '')}",
        f"# 'standard' or 'early_adopter' — controls which pricing experience you see.",
        f"OWNER_PRICING_TIER={config.get('owner_pricing_tier', 'standard')}",
        f"# Populated automatically on first portal startup — do not edit manually.",
        f"OWNER_CUSTOMER_ID={config.get('owner_customer_id', '')}",
        f"STARTING_CAPITAL={config.get('starting_capital', '100')}",
        f"SUPPORT_EMAIL={config.get('support_email', 'synthos.signal@gmail.com')}",
        f"",
        f"# ── PORTAL ────────────────────────────────────────────────────",
        f"PORTAL_PORT={config.get('portal_port', '5001')}",
        f"PORTAL_PASSWORD={config.get('portal_password', '')}",
        f"PORTAL_SECRET_KEY={generated_secret_key}",
        f"# Public URL used to build /setup-account links in setup emails.",
        f"# Set to https://portal.synth-cloud.com when Cloudflare tunnel is active.",
        f"PORTAL_BASE_URL={config.get('portal_base_url', '')}",
        f"",
        f"# ── MONITOR / DEAD MAN SWITCH ─────────────────────────────────",
        f"MONITOR_URL={config.get('monitor_url', '')}",
        f"MONITOR_TOKEN={config.get('monitor_token', 'changeme')}",
        f"",
        f"# ── COMPANY NODE (Scoop queue) ────────────────────────────────",
        f"# Set to http://<company-pi-ip>:5010 to route Scoop events direct.",
        f"# If unset, events proxy via MONITOR_URL (monitor must have COMPANY_URL set).",
        f"COMPANY_URL={config.get('company_url', '')}",
        f"",
        f"# ── ALERTS (RESEND) ───────────────────────────────────────────",
        f"RESEND_API_KEY={config.get('resend_key', '')}",
        f"ALERT_FROM={config.get('alert_from', '')}",
        f"USER_EMAIL={config.get('user_email', '')}",
        f"",
        f"# ── SMS ALERTS (GMAIL GATEWAY) ────────────────────────────────",
        f"GMAIL_USER={config.get('gmail_user', '')}",
        f"GMAIL_APP_PASSWORD={config.get('gmail_app_password', '')}",
        f"ALERT_PHONE={config.get('alert_phone', '')}",
        f"CARRIER_GATEWAY={config.get('carrier_gateway', 'tmomail.net')}",
        f"",
        f"# ── PORTAL ADVANCED SETTINGS (written by portal /api/settings) ─",
        f"CLOSE_SESSION_MODE=conservative",
        f"MAX_POSITION_PCT=0.10",
        f"MAX_SECTOR_PCT=25",
        f"",
        f"# ── GITHUB (optional — for sync.py) ──────────────────────────",
        f"GITHUB_TOKEN={config.get('github_token', '')}",
        f"",
    ]
    return "\n".join(lines)


def build_company_env(config: dict) -> str:
    """
    Build the .env file content for a Company Node (Pi 4B).
    Used by company_server.py (Flask, port 5010) and scoop.py (queue drain daemon).
    Returns the full file content as a string.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        f"# Synthos Company Node — Environment Configuration",
        f"# Generated by install_company.py on {now}",
        f"# DO NOT SHARE — contains company secrets",
        f"# chmod 600 enforced by installer",
        f"",
        f"# ── NODE IDENTITY ─────────────────────────────────────────────",
        f"COMPANY_MODE=true",
        f"SECRET_TOKEN={config.get('secret_token', '')}",
        f"PORT={config.get('port', '5010')}",
        f"",
        f"# ── DATABASE ──────────────────────────────────────────────────",
        f"COMPANY_DB_PATH={config.get('company_db_path', '')}",
        f"",
        f"# ── RESEND (Scoop email dispatch) ─────────────────────────────",
        f"RESEND_API_KEY={config.get('resend_key', '')}",
        f"ALERT_FROM={config.get('alert_from', '')}",
        f"ALERT_TO={config.get('alert_to', '')}",
        f"OPS_EMAIL={config.get('ops_email', '')}",
        f"OPERATOR_EMAIL={config.get('operator_email', '')}",
        f"",
        f"# ── SCOOP SETTINGS ────────────────────────────────────────────",
        f"# Master dispatch switch. Set to true when ready to receive email alerts.",
        f"SCOOP_ENABLED={config.get('scoop_enabled', 'false')}",
        f"# Minimum priority to dispatch: 0=critical only  1=+high  2=+medium  3=all",
        f"SCOOP_MIN_PRIORITY={config.get('scoop_min_priority', '0')}",
        f"SCOOP_POLL_S={config.get('scoop_poll_s', '5')}",
        f"SCOOP_MAX_ATTEMPTS={config.get('scoop_max_attempts', '3')}",
        f"SCOOP_RETRY_DELAY_S={config.get('scoop_retry_delay_s', '60')}",
        f"SCOOP_DRY_RUN={config.get('scoop_dry_run', 'false')}",
        f"",
        f"# ── STRONGBOX SETTINGS ────────────────────────────────────────",
        f"# Hours before a missing backup triggers a CRITICAL alert (default 48).",
        f"STRONGBOX_STALE_HOURS={config.get('strongbox_stale_hours', '48')}",
        f"# Days of pi_events heartbeat history to keep in company.db (default 30).",
        f"PI_EVENTS_RETAIN_DAYS={config.get('pi_events_retain_days', '30')}",
        f"",
    ]
    return "\n".join(lines)
